// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class JoinSessionSessionVideoID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JoinSessionSessionVideoID));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111055178_JoinSession + Session.VideoID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
